version: '3'

services:

  postgres-keycloak:
    image: "postgres:12"
    volumes:
      - db_data_keycloak:/var/lib/postgresql/data
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

  keycloak:
    image: jboss/keycloak:16.1.1
    volumes:
      - ./keycloak/import:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak

volumes:
  db_data:
  db_data_keycloak: